# PR Labeler Configuration
# Automatically labels PRs based on changed files

"module:core":
  - changed-files:
    - any-glob-to-any-file: ['config/**', 'manage.py']

"module:accounts":
  - changed-files:
    - any-glob-to-any-file: 'apps/accounts/**'

"module:itinerary":
  - changed-files:
    - any-glob-to-any-file: 'apps/itinerary/**'

"infra":
  - changed-files:
    - any-glob-to-any-file: ['.github/**', 'requirements.txt', '.gitignore', '.env.example']

"docs":
  - changed-files:
    - any-glob-to-any-file: ['*.md', '.claude/**']

"test":
  - changed-files:
    - any-glob-to-any-file: ['**/tests/**', '**/tests.py']
