- name: "feat"
  color: "0E8A16"
  description: "New features or functionality"
- name: "fix"
  color: "D93F0B"
  description: "Bug fixes"
- name: "infra"
  color: "1D76DB"
  description: "CI/CD, GitHub Actions, Settings, or Environment changes"
- name: "refactor"
  color: "5319E7"
  description: "Code changes that neither fix bugs nor add features"
- name: "docs"
  color: "006B75"
  description: "Documentation updates (README, API docs, .claude/)"
- name: "test"
  color: "FBCA04"
  description: "Adding or updating tests"
- name: "chore"
  color: "D4C5F9"
  description: "Routine tasks, maintenance, or dependency updates"
- name: "security"
  color: "E11D21"
  description: "Security vulnerabilities or hardening"
- name: "module:accounts"
  color: "BFDADC"
  description: "Changes related to the accounts app"
- name: "module:itinerary"
  color: "BFDADC"
  description: "Changes related to the itinerary app"
- name: "module:core"
  color: "BFDADC"
  description: "Changes related to project configuration or core files"
- name: "p0:critical"
  color: "B60205"
  description: "Immediate attention required"
- name: "p1:high"
  color: "D93F0B"
  description: "High priority"
- name: "p2:medium"
  color: "FBCA04"
  description: "Standard priority"
- name: "p3:low"
  color: "0E8A16"
  description: "Nice to have"
- name: "breaking-change"
  color: "B60205"
  description: "Changes that break backward compatibility"
