# Generated by Django 4.2 on 2025-12-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_organization_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='token',
            field=models.CharField(default='d28a7b27b7ec4958a07a72caff6a0dcf', max_length=32, unique=True),
        ),
    ]
