# Generated by Django 4.2 on 2026-01-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_invite_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="token",
            field=models.CharField(
                default="fea7261aa8104223ae185eac95edc660", max_length=32, unique=True
            ),
        ),
    ]
