# Generated by Django 4.2 on 2026-01-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_invite_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="token",
            field=models.CharField(
                default="5b8beac42bbe48e4b45cf03ff8465180", max_length=32, unique=True
            ),
        ),
    ]
