# Generated by Django 4.2 on 2026-01-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_invite_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="token",
            field=models.CharField(
                default="cbbcb3ceeea9460fbe9fa6716b1bbf7e", max_length=32, unique=True
            ),
        ),
    ]
