# Generated by Django 4.2 on 2026-01-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_invite_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="token",
            field=models.CharField(
                default="ed70c90e07864579a7851f44ac826f42", max_length=32, unique=True
            ),
        ),
    ]
