# Generated by Django 4.2 on 2026-01-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_invite_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="token",
            field=models.CharField(
                default="7f6b2846a1ad43b08397f0a472111642", max_length=32, unique=True
            ),
        ),
        migrations.AlterModelTable(
            name="organization",
            table="organizations",
        ),
    ]
