# Generated by Django 4.2 on 2026-01-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_invite_token_alter_organization_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="token",
            field=models.CharField(
                default="6b1609ea0cea4b869c0d2c7e20f4eef0", max_length=32, unique=True
            ),
        ),
    ]
