# Generated by Django 4.2 on 2026-01-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itinerary", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Car",
        ),
    ]
