# Generated by Django 4.2 on 2026-01-24 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_invite_token"),
        ("itinerary", "0002_delete_car"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="exclusions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="inclusions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="region",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name="region",
            unique_together={("organization", "name")},
        ),
        migrations.AlterModelTable(
            name="region",
            table="regions",
        ),
        migrations.RemoveField(
            model_name="region",
            name="note",
        ),
    ]
